name: OrderService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - OrderService/*

pool:
  name: my-agents

variables:
  buildConfiguration: 'Release'
  buildVersion: 1.0
  buildRevision: $[counter(variables['buildVersion'], 0)]

stages:
  - stage: BuildStage
    displayName: Build Service
    jobs:
      - job: BuildJob
        displayName: Build OrderService
        steps:
        - script: |
            echo echo '##vso[build.updatebuildnumber]'$(buildVersion).$(buildRevision)
          displayName: Set Build Number

        - task: DotNetCoreCLI@2
          displayName: Restore Packages
          inputs:
            command: restore
            projects: OrderService/**/*.csproj
        - task: DotNetCoreCLI@2
          displayName: Build Service
          inputs:
            command: build
            arguments: --no-restore
            projects: OrderService/**/*.csproj
        - task: DotNetCoreCLI@2
          displayName: Run Tests
          inputs:
            command: test
            arguments: --no-restore --no-build
            projects: OrderService/*.Tests/*.csproj
        - task: DotNetCoreCLI@2
          displayName: Publish Service
          inputs:
            command: publish
            projects: OrderService/OrderService.Api/OrderService.Api.csproj
            arguments: --configuration $(buildConfiguration) --no-restore
            publishWebProjects: false
            zipAfterPublish: false
        
        - task: Docker@2
          displayName: Build And Push Docker Image
          inputs:
            buildContext: OrderService/OrderService.Api
            Dockerfile: OrderService/OrderService.Api/Dockerfile
            containerRegistry: 'shaijusregistry'
            repository: shaijusregistry.azurecr.io/orderservice
            tags: |
              $(Build.BuildNumber)
              latest

            
