name: CustomerService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CustomerService/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: BuildStage
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
        - task: DotNetCoreCLI@2
          displayName: Restore Packages
          inputs:
            command: restore
            projects: CustomerService/**/*.csproj
